import { Session } from "@/types/session";

export const sessions: Session[] = [
  {
    id: "session-001",
    student: "Rahul Sharma",
    date: "2026-07-24",
    topic: "Algebra foundations",
    durationMinutes: 55,
    coach: "Maya Chen",
    notes:
      "Strong recovery after a slow start. Needed extra prompting on word problems.",
    summary: {
      engagement: 78,
      clarity: 74,
      pacing: 72,
    },
    metrics: [
      { label: "Check-in", engagement: 70, clarity: 68, pacing: 66 },
      { label: "Warm-up", engagement: 75, clarity: 72, pacing: 70 },
      { label: "Practice", engagement: 80, clarity: 76, pacing: 73 },
      { label: "Review", engagement: 86, clarity: 80, pacing: 79 },
    ],
  },
  {
    id: "session-002",
    student: "Ananya Patel",
    date: "2026-07-23",
    topic: "Reading comprehension",
    durationMinutes: 50,
    coach: "Maya Chen",
    notes: "Stayed focused throughout. Inference questions were noticeably stronger.",
    summary: {
      engagement: 84,
      clarity: 82,
      pacing: 79,
    },
    metrics: [
      { label: "Check-in", engagement: 80, clarity: 78, pacing: 76 },
      { label: "Passage 1", engagement: 83, clarity: 81, pacing: 77 },
      { label: "Passage 2", engagement: 85, clarity: 83, pacing: 79 },
      { label: "Wrap-up", engagement: 88, clarity: 86, pacing: 84 },
    ],
  },
  {
    id: "session-003",
    student: "John Carter",
    date: "2026-07-22",
    topic: "Geometry revision",
    durationMinutes: 60,
    coach: "Neha Kapoor",
    notes: "Needed support on proofs but handled visual problems well.",
    summary: {
      engagement: 71,
      clarity: 69,
      pacing: 68,
    },
    metrics: [
      { label: "Check-in", engagement: 68, clarity: 66, pacing: 65 },
      { label: "Examples", engagement: 70, clarity: 68, pacing: 67 },
      { label: "Proofs", engagement: 72, clarity: 69, pacing: 66 },
      { label: "Recap", engagement: 74, clarity: 73, pacing: 74 },
    ],
  },
  {
    id: "session-004",
    student: "Priya Nair",
    date: "2026-07-20",
    topic: "Essay structure",
    durationMinutes: 45,
    coach: "Neha Kapoor",
    notes: "Excellent participation. Thesis writing became much sharper by the end.",
    summary: {
      engagement: 88,
      clarity: 85,
      pacing: 83,
    },
    metrics: [
      { label: "Check-in", engagement: 82, clarity: 80, pacing: 79 },
      { label: "Outline", engagement: 86, clarity: 84, pacing: 82 },
      { label: "Drafting", engagement: 89, clarity: 86, pacing: 83 },
      { label: "Feedback", engagement: 93, clarity: 90, pacing: 88 },
    ],
  },
  {
    id: "session-005",
    student: "Amit Verma",
    date: "2026-07-19",
    topic: "Fractions and ratios",
    durationMinutes: 55,
    coach: "Daniel Brooks",
    notes: "Accuracy improved after visual examples. Pace was uneven early on.",
    summary: {
      engagement: 73,
      clarity: 71,
      pacing: 67,
    },
    metrics: [
      { label: "Check-in", engagement: 66, clarity: 65, pacing: 61 },
      { label: "Concepts", engagement: 70, clarity: 69, pacing: 64 },
      { label: "Practice", engagement: 76, clarity: 73, pacing: 69 },
      { label: "Review", engagement: 80, clarity: 77, pacing: 74 },
    ],
  },
  {
    id: "session-006",
    student: "Sara Khan",
    date: "2026-07-17",
    topic: "Vocabulary building",
    durationMinutes: 40,
    coach: "Daniel Brooks",
    notes: "Confident and fast-paced session. Strong recall from last week.",
    summary: {
      engagement: 90,
      clarity: 87,
      pacing: 88,
    },
    metrics: [
      { label: "Check-in", engagement: 85, clarity: 82, pacing: 84 },
      { label: "Flashcards", engagement: 89, clarity: 86, pacing: 87 },
      { label: "Usage", engagement: 91, clarity: 88, pacing: 89 },
      { label: "Recap", engagement: 95, clarity: 92, pacing: 92 },
    ],
  },
  {
    id: "session-007",
    student: "David Lee",
    date: "2026-07-15",
    topic: "Physics problem solving",
    durationMinutes: 60,
    coach: "Maya Chen",
    notes: "Good reasoning, but explanation quality dropped on multi-step questions.",
    summary: {
      engagement: 76,
      clarity: 70,
      pacing: 72,
    },
    metrics: [
      { label: "Check-in", engagement: 72, clarity: 68, pacing: 70 },
      { label: "Concepts", engagement: 74, clarity: 70, pacing: 71 },
      { label: "Problems", engagement: 77, clarity: 69, pacing: 72 },
      { label: "Debrief", engagement: 81, clarity: 74, pacing: 76 },
    ],
  },
  {
    id: "session-008",
    student: "Emily Wong",
    date: "2026-07-14",
    topic: "Grammar fundamentals",
    durationMinutes: 45,
    coach: "Neha Kapoor",
    notes: "Small mistakes on tense consistency, but overall a smooth session.",
    summary: {
      engagement: 81,
      clarity: 83,
      pacing: 80,
    },
    metrics: [
      { label: "Check-in", engagement: 77, clarity: 79, pacing: 76 },
      { label: "Rules", engagement: 80, clarity: 82, pacing: 79 },
      { label: "Practice", engagement: 82, clarity: 84, pacing: 81 },
      { label: "Review", engagement: 85, clarity: 87, pacing: 84 },
    ],
  },
  {
    id: "session-009",
    student: "Rahul Sharma",
    date: "2026-07-12",
    topic: "Linear equations",
    durationMinutes: 50,
    coach: "Maya Chen",
    notes: "Better confidence than the previous math session. Solved independently more often.",
    summary: {
      engagement: 82,
      clarity: 78,
      pacing: 76,
    },
    metrics: [
      { label: "Check-in", engagement: 75, clarity: 72, pacing: 71 },
      { label: "Examples", engagement: 80, clarity: 76, pacing: 74 },
      { label: "Practice", engagement: 84, clarity: 79, pacing: 77 },
      { label: "Wrap-up", engagement: 89, clarity: 84, pacing: 82 },
    ],
  },
  {
    id: "session-010",
    student: "Ananya Patel",
    date: "2026-07-10",
    topic: "Poetry analysis",
    durationMinutes: 45,
    coach: "Daniel Brooks",
    notes: "Strong interpretation skills. Needed a little more time to articulate evidence.",
    summary: {
      engagement: 86,
      clarity: 80,
      pacing: 77,
    },
    metrics: [
      { label: "Check-in", engagement: 81, clarity: 75, pacing: 74 },
      { label: "Reading", engagement: 85, clarity: 79, pacing: 76 },
      { label: "Discussion", engagement: 88, clarity: 82, pacing: 78 },
      { label: "Summary", engagement: 90, clarity: 85, pacing: 81 },
    ],
  },
  {
    id: "session-011",
    student: "John Carter",
    date: "2026-07-08",
    topic: "Statistics basics",
    durationMinutes: 55,
    coach: "Neha Kapoor",
    notes: "Median and mean were solid. Interpreting charts still needs repetition.",
    summary: {
      engagement: 74,
      clarity: 72,
      pacing: 70,
    },
    metrics: [
      { label: "Check-in", engagement: 69, clarity: 68, pacing: 66 },
      { label: "Examples", engagement: 72, clarity: 71, pacing: 68 },
      { label: "Charts", engagement: 74, clarity: 70, pacing: 69 },
      { label: "Review", engagement: 81, clarity: 79, pacing: 77 },
    ],
  },
  {
    id: "session-012",
    student: "Priya Nair",
    date: "2026-07-06",
    topic: "Creative writing",
    durationMinutes: 50,
    coach: "Daniel Brooks",
    notes: "Very expressive session. The pacing dipped slightly during revision.",
    summary: {
      engagement: 87,
      clarity: 84,
      pacing: 78,
    },
    metrics: [
      { label: "Check-in", engagement: 83, clarity: 80, pacing: 77 },
      { label: "Brainstorm", engagement: 88, clarity: 85, pacing: 80 },
      { label: "Drafting", engagement: 90, clarity: 86, pacing: 78 },
      { label: "Revision", engagement: 87, clarity: 85, pacing: 76 },
    ],
  },
  {
    id: "session-013",
    student: "Amit Verma",
    date: "2026-07-04",
    topic: "Decimals and percentages",
    durationMinutes: 55,
    coach: "Maya Chen",
    notes: "More engaged once the session moved to real-world examples.",
    summary: {
      engagement: 77,
      clarity: 75,
      pacing: 73,
    },
    metrics: [
      { label: "Check-in", engagement: 70, clarity: 69, pacing: 67 },
      { label: "Concepts", engagement: 75, clarity: 73, pacing: 71 },
      { label: "Application", engagement: 79, clarity: 77, pacing: 75 },
      { label: "Recap", engagement: 84, clarity: 81, pacing: 79 },
    ],
  },
  {
    id: "session-014",
    student: "Sara Khan",
    date: "2026-07-03",
    topic: "Speaking confidence",
    durationMinutes: 40,
    coach: "Neha Kapoor",
    notes: "High energy session with clear improvement in fluency.",
    summary: {
      engagement: 92,
      clarity: 88,
      pacing: 90,
    },
    metrics: [
      { label: "Check-in", engagement: 87, clarity: 83, pacing: 85 },
      { label: "Prompts", engagement: 91, clarity: 87, pacing: 89 },
      { label: "Role-play", engagement: 94, clarity: 90, pacing: 91 },
      { label: "Reflection", engagement: 96, clarity: 92, pacing: 94 },
    ],
  },
  {
    id: "session-015",
    student: "David Lee",
    date: "2026-07-01",
    topic: "Chemistry equations",
    durationMinutes: 60,
    coach: "Daniel Brooks",
    notes: "Balanced equations correctly after coaching, but pace slowed during harder items.",
    summary: {
      engagement: 75,
      clarity: 73,
      pacing: 69,
    },
    metrics: [
      { label: "Check-in", engagement: 70, clarity: 69, pacing: 66 },
      { label: "Examples", engagement: 73, clarity: 72, pacing: 68 },
      { label: "Balancing", engagement: 76, clarity: 74, pacing: 69 },
      { label: "Review", engagement: 81, clarity: 78, pacing: 73 },
    ],
  },
  {
    id: "session-016",
    student: "Emily Wong",
    date: "2026-06-29",
    topic: "Sentence construction",
    durationMinutes: 45,
    coach: "Maya Chen",
    notes: "Clear upward trend across the session. Good retention from prior lessons.",
    summary: {
      engagement: 83,
      clarity: 85,
      pacing: 82,
    },
    metrics: [
      { label: "Check-in", engagement: 78, clarity: 80, pacing: 77 },
      { label: "Examples", engagement: 81, clarity: 84, pacing: 80 },
      { label: "Practice", engagement: 84, clarity: 86, pacing: 83 },
      { label: "Wrap-up", engagement: 89, clarity: 90, pacing: 88 },
    ],
  },
  {
    id: "session-017",
    student: "Rahul Sharma",
    date: "2026-06-27",
    topic: "Problem-solving strategies",
    durationMinutes: 50,
    coach: "Neha Kapoor",
    notes: "Needed encouragement at first, but persistence was much better by the end.",
    summary: {
      engagement: 79,
      clarity: 76,
      pacing: 74,
    },
    metrics: [
      { label: "Check-in", engagement: 71, clarity: 69, pacing: 68 },
      { label: "Strategy", engagement: 77, clarity: 74, pacing: 72 },
      { label: "Practice", engagement: 81, clarity: 78, pacing: 75 },
      { label: "Reflection", engagement: 87, clarity: 83, pacing: 81 },
    ],
  },
  {
    id: "session-018",
    student: "Ananya Patel",
    date: "2026-06-25",
    topic: "Summarisation skills",
    durationMinutes: 50,
    coach: "Maya Chen",
    notes: "Solid comprehension throughout. Clarity improved with sentence frames.",
    summary: {
      engagement: 85,
      clarity: 83,
      pacing: 80,
    },
    metrics: [
      { label: "Check-in", engagement: 80, clarity: 77, pacing: 76 },
      { label: "Reading", engagement: 83, clarity: 81, pacing: 79 },
      { label: "Summary", engagement: 86, clarity: 84, pacing: 81 },
      { label: "Review", engagement: 90, clarity: 88, pacing: 85 },
    ],
  },
  {
    id: "session-019",
    student: "Priya Nair",
    date: "2026-06-22",
    topic: "Argument building",
    durationMinutes: 55,
    coach: "Daniel Brooks",
    notes: "Strong opinions and examples. Needed reminders to keep arguments structured.",
    summary: {
      engagement: 84,
      clarity: 79,
      pacing: 77,
    },
    metrics: [
      { label: "Check-in", engagement: 79, clarity: 74, pacing: 73 },
      { label: "Planning", engagement: 82, clarity: 77, pacing: 75 },
      { label: "Writing", engagement: 85, clarity: 80, pacing: 77 },
      { label: "Feedback", engagement: 90, clarity: 85, pacing: 83 },
    ],
  },
  {
    id: "session-020",
    student: "Amit Verma",
    date: "2026-06-20",
    topic: "Data interpretation",
    durationMinutes: 55,
    coach: "Neha Kapoor",
    notes: "Bar charts were comfortable; comparison questions needed extra time.",
    summary: {
      engagement: 72,
      clarity: 70,
      pacing: 68,
    },
    metrics: [
      { label: "Check-in", engagement: 66, clarity: 65, pacing: 63 },
      { label: "Reading", engagement: 70, clarity: 69, pacing: 66 },
      { label: "Comparison", engagement: 73, clarity: 70, pacing: 67 },
      { label: "Recap", engagement: 79, clarity: 76, pacing: 76 },
    ],
  },
];
